
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import serviceLevel.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kiker
 */
public class JFrame_DriverRequestConstructor extends javax.swing.JFrame
{

    private final Session session;
    private final SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    private final SimpleDateFormat df2 = new SimpleDateFormat("dd.MM.yyyy HH:mm");

    /**
     * Creates new form DriverRequestConstructor
     */
    public JFrame_DriverRequestConstructor(Session session)
    {
        initComponents();
        this.session = session;

        jFormattedTextField_enterDate.setText(df.format(new Date()));

        try
        {
            List<Object> parkings = Utils.getUserService().getAllParkings(session);

            for (Object p : parkings)
            {
                jComboBox_selectParking.addItem(((Object[]) p)[0]);
            }

        } catch (RemoteException | NotBoundException ex)
        {
            Logger.getLogger(JFrame_DriverRequestConstructor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel_enterDate = new javax.swing.JLabel();
        jFormattedTextField_enterDate = new javax.swing.JFormattedTextField();
        jFormattedTextField_enterTime = new javax.swing.JFormattedTextField();
        jLabel_enterTime1 = new javax.swing.JLabel();
        jFormattedTextField_leaveTime = new javax.swing.JFormattedTextField();
        jLabel_enterTime2 = new javax.swing.JLabel();
        jLabel_enterDate1 = new javax.swing.JLabel();
        jComboBox_selectParking = new javax.swing.JComboBox();
        jLabel_enterDate2 = new javax.swing.JLabel();
        jButton_createDR = new javax.swing.JButton();
        jSpinner_freePlaces = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel_enterDate.setText("Enter date");

        jFormattedTextField_enterDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jFormattedTextField_enterTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField_enterTime.setText("12:00");

        jLabel_enterTime1.setText("Enter time");

        jFormattedTextField_leaveTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField_leaveTime.setText("13:00");

        jLabel_enterTime2.setText("Leave time");

        jLabel_enterDate1.setText("Free places");

        jLabel_enterDate2.setText("Parking");

        jButton_createDR.setText("Accept");
        jButton_createDR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_createDRActionPerformed(evt);
            }
        });

        jSpinner_freePlaces.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_enterDate)
                                .addComponent(jLabel_enterDate1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jFormattedTextField_enterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_enterTime2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFormattedTextField_leaveTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_enterTime1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFormattedTextField_enterTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jSpinner_freePlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel_enterDate2)
                        .addComponent(jComboBox_selectParking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_createDR, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_enterDate)
                    .addComponent(jFormattedTextField_enterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_enterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_enterTime1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_leaveTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_enterTime2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_enterDate1)
                    .addComponent(jSpinner_freePlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_enterDate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_selectParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_createDR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_createDRActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_createDRActionPerformed
    {//GEN-HEADEREND:event_jButton_createDRActionPerformed
        try
        {
            String enterDate = jFormattedTextField_enterDate.getText() + " " + jFormattedTextField_enterTime.getText();
            String leaveDate = jFormattedTextField_enterDate.getText() + " " + jFormattedTextField_leaveTime.getText();

            Map<String, Object> map = new HashMap();
            map.put("entryDate", df2.parse(enterDate));
            map.put("leaveDate", df2.parse(leaveDate));
            map.put("freePlaces",jSpinner_freePlaces.getValue());
            map.put("address", jComboBox_selectParking.getSelectedItem());

            Utils.getUserService().createDriverRequest(session, map);
            
           
        } catch (Exception ex)
        {
            Logger.getLogger(JFrame_DriverRequestConstructor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error while processing your request. Try again.");
            
        }
        finally
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_createDRActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_createDR;
    private javax.swing.JComboBox jComboBox_selectParking;
    private javax.swing.JFormattedTextField jFormattedTextField_enterDate;
    private javax.swing.JFormattedTextField jFormattedTextField_enterTime;
    private javax.swing.JFormattedTextField jFormattedTextField_leaveTime;
    private javax.swing.JLabel jLabel_enterDate;
    private javax.swing.JLabel jLabel_enterDate1;
    private javax.swing.JLabel jLabel_enterDate2;
    private javax.swing.JLabel jLabel_enterTime1;
    private javax.swing.JLabel jLabel_enterTime2;
    private javax.swing.JSpinner jSpinner_freePlaces;
    // End of variables declaration//GEN-END:variables
}
